//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoExamen2026.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DemoEcsamenDBEntities : DbContext
    {
        public DemoEcsamenDBEntities()
            : base("name=DemoEcsamenDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CategoryTable> CategoryTable { get; set; }
        public virtual DbSet<ManufacturerTable> ManufacturerTable { get; set; }
        public virtual DbSet<MeasurementTable> MeasurementTable { get; set; }
        public virtual DbSet<OrderTable> OrderTable { get; set; }
        public virtual DbSet<OrderToTovarTable> OrderToTovarTable { get; set; }
        public virtual DbSet<ProductTable> ProductTable { get; set; }
        public virtual DbSet<ProviderTable> ProviderTable { get; set; }
        public virtual DbSet<RoleTable> RoleTable { get; set; }
        public virtual DbSet<StatusTable> StatusTable { get; set; }
        public virtual DbSet<StreetTable> StreetTable { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TovarTable> TovarTable { get; set; }
        public virtual DbSet<UserTable> UserTable { get; set; }
    }
}
