//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoExamen2026.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderToTovarTable
    {
        public int ID { get; set; }
        public int OrderID { get; set; }
        public int TovarID { get; set; }
        public int Amount { get; set; }
    
        public virtual OrderTable OrderTable { get; set; }
        public virtual TovarTable TovarTable { get; set; }
    }
}
