//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoExamen2026.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TovarTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TovarTable()
        {
            this.OrderToTovarTable = new HashSet<OrderToTovarTable>();
        }
    
        public int ID { get; set; }
        public string Articule { get; set; }
        public int ProductID { get; set; }
        public int MeasurementID { get; set; }
        public int Price { get; set; }
        public int ProviderID { get; set; }
        public int ManufacturerID { get; set; }
        public int CategoryID { get; set; }
        public int Discount { get; set; }
        public int Count { get; set; }
        public string Commentary { get; set; }
        public string Photo { get; set; }
    
        public virtual CategoryTable CategoryTable { get; set; }
        public virtual ManufacturerTable ManufacturerTable { get; set; }
        public virtual MeasurementTable MeasurementTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderToTovarTable> OrderToTovarTable { get; set; }
        public virtual ProductTable ProductTable { get; set; }
        public virtual ProviderTable ProviderTable { get; set; }
    }
}
